config/routes.rb
Rails.application.routes.draw do
  get 'images' => 'images#index'
  
  resources :albums do
    resources :images
  end
  # get 'append_image' => 'albums#append_image'
  get 'pages/about', to: 'pages#show_or_set'
  resources :pages, except: :index
  root 'albums#index' # 'pages#welcome'
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_and_belongs_to_many :images
  accepts_nested_attributes_for :images,
                                allow_destroy: true,
                                reject_if: :all_blank
  # reject_if: lambda {|attributes| attributes['picture'].blank?}
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_and_belongs_to_many :albums

  has_attached_file :picture, styles: {
    large: '900x900>',
    medium: '300x300',
    thumb: '100x100#' }

  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  validates :picture, presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates :title, presence: true
  before_save :downcase_title

  extend FriendlyId   # def to_params
  friendly_id :title # , use: :slugged

  private

  def downcase_title
    self.title = title.downcase
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: Rails.application.secrets.admin_login,
                               password: Rails.application.secrets.admin_pwd,
                               except: [:show, :index]

  # GET /albums
  def index
    @albums = Album.all
  end

  # GET /albums/1
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
    @images = @album.images.build # Array.new(3) { @album.images.build }
  end

  # GET /albums/1/edit
  def edit
    @album.images.build

    respond_to do |format|
      format.html
      format.js
    end
  end

  # def append_image
  #   @album ||= Album.new
  #   respond_to do |format|
  #     format.js
  #   end
  # end

  # POST /albums
  def create
    @album = Album.new album_params

    # raise
    if @album.save
      redirect_to @album, notice: 'Album was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /albums/1
  def update
    # raise
    if @album.update album_params
      redirect_to @album, notice: 'Album was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /albums/1
  def destroy
    @album.destroy
    redirect_to albums_url, notice: 'Album was successfully destroyed.'
  end

  private

  def set_album
    @album = Album.find params[:id]
  end

  def album_params
    params.require(:album).permit :title,
                                  :description,
                                  images_attributes:
                                  [:id, :description, :picture, :_destroy]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  def index
    @images = Image.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: Rails.application.secrets.admin_login,
                               password: Rails.application.secrets.admin_pwd,
                               except: [:show, :index, :show_or_set]

  # GET /pages/1
  def show
  end

  # def welcome
  #   # @page = Page.find_by title: 'welcome'
  #   @page = Page.where("title like ?", "%welcome%").first
  #   if @page
  #     render :show
  #   else
  #     @page = Page.new title: 'Welcome'
  #     # redirect_to new_page_path, alert: 'Create a welcome page first!'
  #     flash.now[:alert]= 'Create a welcome page first!'
  #     render :new
  #   end
  # end

  def show_or_set
    # like params[:id]
    @page = Page.where('title like ?', '%about%').first
    if @page
      render :show
    else
      @page = Page.new title: 'About'
      flash.now[:alert] = 'Create About page first!'
      render :new
    end
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  def create
    @page = Page.new page_params
    respond_to do |format|
      if @page.save
        flash[:notice] = 'Page was successfully created.'
        format.html { redirect_to @page }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /pages/1
  def update
    respond_to do |format|
      if @page.update page_params
        flash[:notice] = 'Page was successfully updated.'
        format.html { redirect_to @page }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /pages/1
  def destroy
    @page.destroy
    respond_to do |format|
      flash[:notice] = 'Page was successfully destroyed.'
      format.html { redirect_to root_path }
    end
  end

  private

  def set_page
    @page = Page.friendly.find params[:id].to_s.downcase
  end

  def page_params
    params.require(:page).permit(:title, :body)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/albums/_form.html.slim
= form_for @album do |album_form|
  - #album_form.error_notification

  .form-inputs
    .form-group
      = album_form.label :title
      = album_form.text_field :title, class: 'form-control', autofocus: true
    .form-group
      = album_form.label :description
      = album_form.text_area :description, class: 'form-control'

  hr
  #images
    = album_form.fields_for :images do |img_f|
      = render 'image_fields', f: img_f

  .form-actions
    .btn-group
      - # link_to 'More Images', append_image_path, remote: true, class: 'btn'
      = link_to_add_association 'More Images', album_form, :images, class: 'btn'
      = album_form.submit class: 'btn btn-primary'
      = link_to 'Cancel', @album.new_record? ? albums_path : @album, class: 'btn btn-default'

/ = simple_form_for @album do |f| 
/   = f.input :title
/   = f.input :description

/   =f.simple_fields_for :images do |imgf|    
/     p.pic
/       = image_tag imgf.object.send(:picture).send :url, :thumb
/       / picture.
/       = imgf.input :picture
/     = imgf.input :description

/   - #f.association :images
/   = f.button :submit 

app/views/albums/_image_fields.html.slim
.nested-fields
  .panel.panel-default
    .panel-heading
      | Image
    .panel-body
      - unless f.object.new_record?
        .form-inputs
          = image_tag f.object.send(:picture).send :url, :thumb 
        / .form-inputs
        /   | Mark do delete: 
        /   = f.check_box :_destroy
      .form-group
        = f.label :picture, "#{f.object.new_record? ? 'Add' : 'Change'} picture"
        = f.file_field :picture
      .form-group.form-inputs
        = f.label :description, 'Picture title'
        = f.text_field :description, class: 'form-control'

    .panel-footer
      = link_to_remove_association "Remove image", f

app/views/albums/edit.html.slim
h1 Editing album

== render 'form'

app/views/albums/index.html.slim
- @albums.each do |album|
    .article
      h1= link_to album.title, album
      p = album.description

      - if album.images.any?
        .images
          = link_to album do
            - album.images.limit(3).each do |img|
              = image_tag img.picture.url(:thumb)
      hr

= content_for :navbar_right
  = link_to 'New Album', new_album_path, class: 'btn btn-primary navbar-btn'

app/views/albums/new.html.slim
h1 New album

== render 'form'

app/views/albums/show.html.slim
h1= @album.title
p= @album.description

= render @album.images
= render 'shared/gallery'

- content_for :footer
  = link_to '← Back to albums', albums_path

  .btn-group.controls.gallery-controls
    = link_to edit_album_path(@album), {class: "btn btn-warning btn-xs"} do
      span.glyphicon.glyphicon-pencil(aria-hidden="true")
      | Edit
    = link_to @album, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" do
      span.glyphicon.glyphicon-remove(aria-hidden="true")
      | Destroy

app/views/images/_image.html.slim
/ figure.image
/   = image_tag image.picture.url(:medium)
/   figcaption= image.description 

= link_to image.picture.url(:large), title: image.description, data: {gallery: ''} do
  = image_tag image.picture.url(:thumb)

app/views/images/index.html.slim
article
  h1 All images
  #links
    = render @images

= render 'shared/gallery'

- content_for :bottom do  
  -# javascript_include_tag '/vendor/assets/gallery/js/bootstrap-image-gallery.min'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Gallery
    = stylesheet_link_tag "//blueimp.github.io/Gallery/css/blueimp-gallery.min.css"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body

    nav.navbar.navbar-default
      .container
        .navbar-header
          = link_to 'Simple Gallery', root_path, class: 'navbar-brand'
        ul.nav.navbar-nav
          - # li(class="#{'active' if current_page?(albums_path)}")= link_to 'Albums', albums_path
          li(class="#{'active' if current_page?('/pages/about')}")= link_to 'About', '/pages/about'
        ul.nav.navbar-nav.navbar-right
          = yield :navbar_right

    article.container
      .row
        = render 'shared/notice'

        = yield

    footer.footer
      = yield :footer

app/views/pages/_form.html.slim
= simple_form_for(@page) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :body

  .form-actions
    = f.button :submit

app/views/pages/edit.html.slim
h1 Editing page

== render 'form'

= link_to 'Show', @page
'|
= link_to 'Back', root_path

app/views/pages/new.html.slim
h1 New page

== render 'form'

= link_to 'Back', root_path

app/views/pages/show.html.slim
- cache @page do
  article
    h1= @page.title.mb_chars.capitalize
    p= simple_format @page.body

app/views/shared/_gallery.html.slim
#blueimp-gallery.blueimp-gallery(data-use-bootstrap-modal="false")
  .slides
  / controls
  h3.title
  a.prev ‹
  a.next ›
  a.close ×
  a.play-pause
  ol.indicator

  .modal.fade
    .modal-dialog
      .modal-content
        .modal-header
          button.close(type='button' aria-hidden="true") &times;
          h4.modal-title
        .modal-body.next
        .modal-footer
          button.btn.btn-default.pull-left.prev(type='button' aria-hidden="true")
            i.glyphicon.glyphicon-chevron-left Previous
          button.btn.btn-primary.next(type='button' aria-hidden="true")          
            i.glyphicon.glyphicon-chevron-right Next 

app/views/shared/_notice.html.slim
- if notice || alert
  .alert.alert-dismissible(role='alert' class="alert-#{alert ? 'danger' : 'info'}")
    = notice || alert
    button.close(type='button' data-dismiss='alert' aria-label='Close')
      span(aria-hidden='true') &times;